# Generated by Django 3.1.7 on 2021-03-24 20:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote_id', models.IntegerField(default=-1)),
                ('error_code', models.IntegerField(default=-1)),
                ('message', models.CharField(max_length=200)),
                ('operation', models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')])),
            ],
        ),
    ]
