# Generated by Django 3.1.7 on 2021-03-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210324_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotelog',
            name='error_code',
        ),
    ]
