# Generated by Django 3.1.7 on 2021-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210322_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='deletedAt',
            field=models.DateTimeField(default=None),
        ),
    ]
