# Generated by Django 3.1.7 on 2021-03-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quotelog_err_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotelog',
            old_name='err_code',
            new_name='error_code',
        ),
    ]
