# Generated by Django 3.1.7 on 2021-03-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210325_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotelog',
            name='message',
        ),
    ]
