# Generated by Django 3.1.7 on 2021-03-24 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210322_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote_id', models.IntegerField()),
                ('error_code', models.IntegerField()),
                ('message', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
