# Generated by Django 3.1.7 on 2021-03-25 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_quotelog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelog',
            name='message',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None),
        ),
    ]
