# Generated by Django 3.1.7 on 2021-03-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quotelog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='price',
        ),
    ]
