# Generated by Django 3.1.7 on 2021-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quotelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelog',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=1),
        ),
    ]
