# Generated by Django 3.1.7 on 2021-03-25 13:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_quote_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.IntegerField(default=0, validators=[api.models.Quote.validation_positive]),
        ),
    ]
