# Generated by Django 3.1.7 on 2021-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210324_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelog',
            name='operation',
            field=models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')]),
        ),
    ]
