# Generated by Django 3.1.7 on 2021-03-25 15:01

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quote_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='price',
            field=models.IntegerField(validators=[api.models.Quote.validation_positive]),
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='error_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='message',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
