# Generated by Django 3.1.7 on 2021-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210324_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelog',
            name='error_code',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='quote_id',
            field=models.IntegerField(default=-1),
        ),
    ]
